language: minimal
os:
  - linux
dist: xenial
addons:
  apt:
    update: true
before_install:
 - sudo pip install --upgrade pip
 - sudo apt-get install dos2unix
 # command to run tests
script:
 - sudo chmod +x head_start.sh
 - sudo ./head_start.sh
 - sudo cp -a bash_support/. ~
